version: "3.7"
services:
  trec-service:
    build:
      context: ../trec-service
    environment: 
      TREC_INIT_INDEX: 1
      TREC_SERVER: 1
    ports:
      - "8001:8001"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      discovery.type: single-node
      thread_pool.write.queue_size: 2500
      ES_HEAP_SIZE: 30g
    ports:
      - "9200:9200"
    volumes:
      - /storage/jrie/es:/usr/share/elasticsearch/data
    container_name: elasticsearch
